title: Muhamad Sahrul 
logo: "/images/passfoto.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst Enthusiast
  Google Data Analyst Program Course
  <br><br>
  <a href="https://www.linkedin.com/in/sahrul59/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
